[project]
name = "seatbelt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ronanpdh", email = "ronan@rpdh.uk" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
seatbelt = "seatbelt:main"

[build-system]
requires = ["uv_build>=0.11.13,<0.12.0"]
build-backend = "uv_build"
